---
- name: Install Web Stack
  hosts: webservers-nodes
  gather_facts: false
  become: yes
  become_method: su

  tasks:

    - name: Update APT and install base tools
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - procps
          - net-tools

    - name: Install Apache, PHP, MySQL
      apt:
        name:
          - apache2
          - mysql-server
          - python3-pymysql
          - php
          - php-mysql
          - php-mbstring
          - libapache2-mod-php
        state: present

    - name: Ensure MySQL socket directory exists
      file:
        path: /var/run/mysqld
        state: directory
        owner: mysql
        group: mysql
        mode: '0755'

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Configure Apache2 ports (node1)
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen '
        line: 'Listen 8081'
      when: inventory_hostname == 'node1'
      notify: restart apache2

    - name: Configure Apache2 ports (node2)
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen '
        line: 'Listen 8082'
      when: inventory_hostname == 'node2'
      notify: restart apache2

    - name: Overwrite default vhost (node1)
      copy:
        dest: /etc/apache2/sites-available/000-default.conf
        content: |
          <VirtualHost *:8081>
              ServerAdmin webmaster@localhost
              DocumentRoot /var/www/html
              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>
      when: inventory_hostname == 'node1'
      notify: restart apache2

    - name: Overwrite default vhost (node2)
      copy:
        dest: /etc/apache2/sites-available/000-default.conf
        content: |
          <VirtualHost *:8082>
              ServerAdmin webmaster@localhost
              DocumentRoot /var/www/html
              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>
      when: inventory_hostname == 'node2'
      notify: restart apache2

    - name: Create info.php
      copy:
        dest: /var/www/html/info.php
        content: "<?php phpinfo(); ?>"

    - name: Start and enable Apache2
      service:
        name: apache2
        state: started
        enabled: yes

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
